name: Push ticket
on:
  push:
    tags:
      - "*"
jobs:
  Create-SHRITicket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 🦄 Install package jq
        run: sudo apt-get install jq
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - name: ⬇ ️Create ticket
        run: sudo sh ./createTicket.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          XORGID: ${{ secrets.XORGID }}
      - name: ⬇ Start jest-tests
        run: sudo sh ./runTests.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          XORGID: ${{ secrets.XORGID }}